{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Agencia API REST",
    "description" : "Permite gestionar la información de la agencia",
    "termsOfService" : "https://rbsistemas.mx/terms",
    "contact" : {
      "name" : "José Antonio Rodríguez Barceló",
      "url" : "https://rbsistemas.mx",
      "email" : "rbsistemas@hotmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "description" : "Agencia Developer Server",
    "url" : "https://api.shuttleexpressmexico.com.mx/v1/"
  }, {
    "description" : "SwaggerHub API Auto Mocking",
    "url" : "https://virtserver.swaggerhub.com/RB-Sistemas/AgenciaAPI/1.0.0"
  } ],
  "paths" : {
    "/hoteles" : {
      "post" : {
        "tags" : [ "hotel" ],
        "summary" : "Agrega Hotel",
        "description" : "Agrega un nuevo hotel al catálogo",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ],
        "operationId" : "addHotel"
      },
      "put" : {
        "tags" : [ "hotel" ],
        "summary" : "Actualiza Hotel",
        "description" : "Actualiza un hotel en el catálogo",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ],
        "operationId" : "editHotel"
      },
      "get" : {
        "tags" : [ "hotel" ],
        "summary" : "Obtiene Hoteles",
        "operationId" : "getHotel",
        "description" : "Listado de hoteles",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ]
      }
    },
    "/hoteles/filtro" : {
      "get" : {
        "tags" : [ "hotel" ],
        "summary" : "Obtiene Hoteles",
        "description" : "Listado de hoteles por filtro",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ]
      }
    },
    "/hoteles/{hotel_id}" : {
      "get" : {
        "tags" : [ "hotel" ],
        "summary" : "Obtiene Hotel",
        "description" : "Hotel por Id",
        "operationId" : "getHotelById",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ]
      },
      "delete" : {
        "tags" : [ "hotel" ],
        "summary" : "Elimina un hotel",
        "description" : "Elimina un hotel por su Id",
        "operationId" : "deleteHotelById",
        "security" : [ {
          "api_key" : [ "write:hoteles", "read:hoteles" ]
        } ]
      }
    },
    "/password/cambio" : {
      "post" : {
        "tags" : [ "password" ],
        "description" : "Cambia la contraseña del usuario",
        "summary" : "Cambia Contraseña",
        "operationId" : "cambioPasswd",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    },
    "/password/correo" : {
      "post" : {
        "tags" : [ "password" ],
        "summary" : "Envia correo reinicio",
        "description" : "Envia un correo electronico al usuario solicitado para que pueda reinciar su contraseña",
        "security" : [ {
          "api_key" : [ "write:password", "read:password" ]
        } ],
        "operationId" : "sendMail"
      }
    },
    "/password/reinicio" : {
      "post" : {
        "tags" : [ "password" ],
        "summary" : "Reinicia contraseña",
        "description" : "Reinicia la contraseña del usuario",
        "security" : [ {
          "api_key" : [ "write:password", "read:password" ]
        } ],
        "operationId" : "restartPwd"
      }
    },
    "/tokens/invalida" : {
      "post" : {
        "tags" : [ "token" ],
        "summary" : "Invalida Json Web Token",
        "description" : "Invalida el json web token producto del cierre de sesión"
      }
    },
    "/tokens/refresh" : {
      "post" : {
        "tags" : [ "token" ],
        "summary" : "Json Web Token",
        "description" : "Devuelve un nuevo json web token"
      }
    },
    "/usuarios/avatar" : {
      "post" : {
        "tags" : [ "usuario" ],
        "summary" : "Actualiza Avatar",
        "description" : "Carga la imagen del usuario y la actualiza en la bd",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    },
    "/usuarios/invitacion" : {
      "post" : {
        "tags" : [ "usuario" ],
        "summary" : "Invita usuario",
        "description" : "Invita a un usuario a registrarse a traves de un correo electrónico",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    },
    "/usuarios/login" : {
      "post" : {
        "tags" : [ "usuario" ],
        "description" : "Inicio de sesión",
        "summary" : "Login",
        "operationId" : "login"
      }
    },
    "/usuarios/registro" : {
      "post" : {
        "tags" : [ "usuario" ],
        "description" : "Registrar usuario en la base de datos",
        "summary" : "Registra Usuario",
        "operationId" : "regUser"
      }
    },
    "/usuarios" : {
      "get" : {
        "tags" : [ "usuario" ],
        "summary" : "Obtiene Usuarios",
        "description" : "Listado de usuarios",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    },
    "/usuarios/{usr_id}" : {
      "put" : {
        "tags" : [ "usuario" ],
        "summary" : "Actualizar usuario",
        "description" : "Actualiza la información del usuario",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      },
      "get" : {
        "tags" : [ "usuario" ],
        "summary" : "Obtiene Usuario",
        "description" : "Usuario por Id",
        "operationId" : "getUsuarioById",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    },
    "/usuarios/filtro" : {
      "get" : {
        "tags" : [ "usuario" ],
        "summary" : "Obtiene Usuarios",
        "description" : "Listado de usuarios por filtro",
        "security" : [ {
          "api_key" : [ "write:usuarios", "read:usuarios" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "api_key" : {
        "type" : "apiKey",
        "name" : "jwt",
        "in" : "header"
      }
    }
  }
}